### ISSUE TITLE
Zugriff auf ALKIS Plugin nur für authentifizierte Nutzer

### ISSUE THREAD

**Issue by jodeutmann** [norBIT/alkisplugin#11]
Hallo Herr Fischer,

ich habe eine Nutzergruppe, die auf ALKIS Sekundärdaten zugreifen darf. Diese würde ich gerne nutzen, um auch den Zugriff auf die ALKIS Postnasdaten zu regeln. Leider klappt das nicht. Die Gruppe hat zwar dieselben Rechte wie der Adminuser der Postnas, trotzdem gelingt mir der Aufruf der Datenbank nicht. Was mache ich falsch?
![image](https://cloud.githubusercontent.com/assets/8985259/10753510/c752b2ac-7c91-11e5-9b31-6eb008914fc2.png)

Vielen Dank und Grüße
Joachim Deutmann

**Comment by jef-n** [comment]
Hat die Gruppe möglicherweise kein SELECT-Recht auf der ``spatial_ref_sys`` oder ``geometry_columns``-Tabelle?

**Comment by jodeutmann** [comment]
Hallo,

ja, das war die Lösung. Ich habe jetzt allen Tabellen die Nutzergruppe zugewiesen und nun funktioniert der Zugriff auch für die autorisierten Benutzer.

Danke und Grüße
Joachim Deutmann

**Comment by jef-n** [comment]
Bitte schön.
