### ISSUE TITLE
S/W-Darstellung "Flächen (Industrie und Gewerbe)"

### ISSUE THREAD

**Issue by bstroebl** [norBIT/alkisplugin#13]
Moin Jürgen,
die Flächengrenzen des Layers sind in mm angegeben. Da alle anderen Linien in Karteneinheiten sind, stechen die Gewerbeflächen in Massstäben < 1:5000 (ca.) unangenehm heraus.
Grüße

**Comment by jef-n** [comment]
Hier anscheinend nicht.  Hast Du dazu vielleicht noch nähere Informationen (Signaturnummer, Layer, Screenshot)?

**Comment by bstroebl** [comment]
Signaturnummer 1403, Layer "Flächen (Industrie und Gewerbe)"
![1403_m_1_zu_10000](https://cloud.githubusercontent.com/assets/2534601/12613760/f419c002-c4fb-11e5-9a65-37997e492e8c.png)
![1403_m_ca_1_zu_80000](https://cloud.githubusercontent.com/assets/2534601/12613761/f419d18c-c4fb-11e5-93f9-a7c1ea443584.png)

**Comment by bstroebl** [comment]
das obere Bild ist M = 1:10.000, ds untere ca. M = 1:80.000

**Comment by jef-n** [comment]
Auf den Flächenlayern sollten eigentlich gar keine Randlinien dargestellt werden, denn sind auf den "Grenzen"- und ggf. "Linien"-Layern.   Gefixt in 3f27f4c61

**Comment by bstroebl** [comment]
Danke für den fix! In den kleineren Massstäben sieht es immer noch "gewöhnungsbedürftig" aus, was aber daran liegt, dass es (zumindest hier) die einzigen Flächen mit Füllung sind.

**Comment by jef-n** [comment]
ALKIS ist eigentlich auch für große Maßstäbe ausgelegt.   Das in kleineren überhaupt etwas angezeigt wird dient nur zur (ganz groben) Orientierung.

**Comment by bstroebl** [comment]
ist schon klar, in 1:1000 ist die Ansicht ok
