### ISSUE TITLE
Fließrichtungspfeil verkehrt herum

### ISSUE THREAD

**Issue by jodeutmann** [norBIT/alkisplugin#14]
Hallo,

der Fließrichtungspfeil in Gewässern zeigt im ALKIS Plugin in die entgegengesetzte Richtung. Anbei einmal ein ALKIS Auszug aus dem Kataster und ein identischer Auszug aus der Darstellung über das ALKIS Plugin. Die richtige Richtung ist diejenige im amtlichen ALKIS Auszug.

Viele Grüße
Joachim Deutmann
![amtliche alkis karte kreis re](https://cloud.githubusercontent.com/assets/8985259/12952168/cb2d33fc-d015-11e5-9f0f-45a9233ff2b9.jpg)
![nichtamtliche alkis karte uber alkis_plugin](https://cloud.githubusercontent.com/assets/8985259/12952169/cb38c118-d015-11e5-9d04-a2bf6bb91417.jpg)

**Comment by jef-n** [comment]
Das ist vermutlich ein Folgefehler aus dem alkis-import.  Für die Behebung wäre interessant, ob es sich um ein AX_Fliessgewaesser oder ein AX_UntergeordnetesGewaesser handelt und ob es AP_PPO oder AP_LPO dazu gibt (oder ein Auszug der Rohdaten).

**Comment by jodeutmann** [comment]
Hallo,

das trifft beide AX_Klassen. 

Hier ein Beispiel für AX_UntergeordnetesGewaesser.

![image](https://cloud.githubusercontent.com/assets/8985259/12971814/5d03967a-d09f-11e5-8913-0709cc430c96.png)

![image](https://cloud.githubusercontent.com/assets/8985259/12971819/66ab3e80-d09f-11e5-86c2-70c993845460.png)

Die XML-Datei ist beigefügt.

[NBA_Ring_DOGLMA_151203_25von63_364000_5720000.zip](https://github.com/norBIT/alkisplugin/files/126088/NBA_Ring_DOGLMA_151203_25von63_364000_5720000.zip)

Daten zu ax_fliessgewaesser kann ich leider nicht liefern, da die gml_id's, die ich zu den Fließgewässern identifiziert habe, weder in der Ersteinrichtung noch in den NBA Daten finden kann. Aber einen CSV_Export eines Datensatzes aus ax_fliessgewaesser habe ich angefügt.

[fliessgewaesser.zip](https://github.com/norBIT/alkisplugin/files/126108/fliessgewaesser.zip)

Viele Grüße
Joachim Deutmann

**Comment by jodeutmann** [comment]
Hallo Herr Fischer,

das vorgenannte Problem ist bei uns immer noch akut. Da das ALKIS Plugin hier in Dorsten gut in Gebrauch ist, wäre es sehr gut, wenn Sie eine Lösung zur Korrektur der Fließrichtung finden könnten. In letzter Zeit gibt es auch von meinen Anwendern vermehrt Hinweise dazu. Zur Vermeidung von Fehlinterpretationen habe ich die Fließrichtung bereits aus den auf den Daten laufenden WMS Diensten herausgenommen. Im ALKIS Plugin kann ich das ja leider nicht allgemeingültig für alle Anwender (ca. 30) voreinstellen.

![fliessrichtungspfeil](https://cloud.githubusercontent.com/assets/8985259/25987951/65387b44-36f6-11e7-922a-b5970adde8c5.jpg)

Vielen Dank und viele Grüße
Joachim Deutmann

**Comment by jef-n** [comment]
Moin Herr Deutmann,

ich habe nun mal die Daten des Kreises Recklinghausen eingelesen, um das Problem zu verifizieren.

Bei 363712.136,5736194.359 findet sich ein Fließrichtungspfeil mit `drehwinkel` 0.   In QGIS zeigt der Pfeil nach Westen. Nach [Signaturkatalog](http://www.bezreg-koeln.nrw.de/brk_internet/geobasis/liegenschaftskataster/alkis/vorgaben/pflichtenheft_06/pflichtenheft_k/anlage_06_teil_b1_signaturenbibliothek.pdf) zeigt der (ungedrehte) Fließrichtungspfeil (3488; Seite 164/165) auch nach Westen.  Demnach sollte das so stimmen.

Der Örtlichkeit nach sollten die Fließrichtung dort aber eigentlich nach Osten zu den weiteren Gewässern zeigen.

Der [Objektartenkatalog](http://www.bezreg-koeln.nrw.de/brk_internet/geobasis/liegenschaftskataster/alkis/vorgaben/pflichtenheft_03/anlage_03_alkis_nrw_ok_max_v6_0_1.htm#_3AF00F2301F7-_3B67C17C015B) sagt zum Drehwinkel:
> Winkel um den der Text oder die Signatur mit punktförmiger Bezugsgeometrie aus der Horizontalen gedreht ist. Angabe im Bogenmaß; Zählweise im mathematisch positiven Sinn (von Ost über Nord nach West und Süd).
> Das Attribut ist bei Objekterzeugung mit dem Wert 0 vorbelegt.

0 Grad ist also Osten.  Da der ungedrehte Fließrichtungpfeil aber nach Westen zeigt, müßte der Drehwinkel pi() statt 0 sein (oder -pi() - es fällt auf, dass in Recklinghausen die Winkel meist negativ angegeben sind), um ihn der Darstellung nach Osten zeigen zu lassen.

Mir scheint das Problem also an den Daten zu liegen.  Was auch dazu paßt, das dies bisher die einzige Meldung hierzu ist.

**Comment by jodeutmann** [comment]
Hallo Herr Fischer,

danke für die Antwort. Ich habe mir das Objekt auch nochmal im Objektbrowser angesehen:
![image](https://cloud.githubusercontent.com/assets/8985259/26052963/671c46e8-3967-11e7-89cd-39ac34f1c16f.png)
Der Drehwinkel ist dort mit "0" angegeben. Nun zeigt das Symbol "Fließrichtung" in ALKIS nach Osten, im ALKIS Plugin nach Westen. Bei identischem Drehwinkel. 

Ich würde nun darauf schließen, dass für die Darstellung zwei **verschiedene** SVG-Symbole verwendet werden. Im Kataster eines mit der Pfeilspitze rechts und im ALKIS Plugin eines mit der Pfeilspitze links (so wie in der GeoInfoDok gezeigt).

Lösung 1: ändern des Symbols im ALKIS Datenbestand mit gleichzeitigem Ändern des Drehwinkels (Addition von pi auf den vorhandenen Winkelwert)
Lösung 2: ändern des Symbols im ALKIS Plugin. Der Drehwinkel kann dann unverändert bleiben. Diese Lösung könnte allerdings nur hier lokal erfolgen. Natürlich unpraktisch bei Updates des Plugins.

Hier der Ausschnitt aus der SLD für die Katasterkarte:

<PointSymbol>
    <Name>Fliessrichtungspfeil 271@Flurkarte</Name>
    <Geometry>
      <ogc:PropertyName>position</ogc:PropertyName>
        <Presentation>Anfangspunkt</Presentation>
    </Geometry>
    <Graphic>
      <ExternalGraphic>
        <OnlineResource 
          xmlns:xlink="http://www.w3.org/1999/xlink" xlink:type="simple" 
          xlink:href="\svg\sign_3488.svg"/>
        <Format>image/svg</Format>
      </ExternalGraphic>
      <Size>10m</Size>
      <Rotation><ogc:PropertyName>ATT+drehwinkel+ATT+UNT+rad (O=0, N=Pi)+UNT</ogc:PropertyName></Rotation>
      <RotationNull>false</RotationNull>    </Graphic>
  </PointSymbol>
      
Und das hier ist die SVG-Datei dazu:

![image](https://cloud.githubusercontent.com/assets/8985259/26055400/1799102e-3971-11e7-8b8c-3aa80c8274df.png)

**Comment by jodeutmann** [comment]
der SLD Ausschnitt hier nochmal als Screenshot

![image](https://cloud.githubusercontent.com/assets/8985259/26055484/6fe10dea-3971-11e7-8e29-0ffc0010ce52.png)

**Comment by jef-n** [comment]
Kommt darauf an wie man es sieht.  Beides führt zum Ziel - aber IMHO hat nur Lösung 1 den Namen verdient - "Lösung" 2 verschleiert nur das Problem.  Aber für Lösung 1 müßte man zumindest katasterführende Stelle sein.

"Lösung" 3 könnte ein SQL-Skript in postprocessing.d sein:
``
UPDATE po_points SET drehwinkel_grad=-drehwinkel_grad,drehwinkel=-drehwinkel WHERE signaturnummer='3488';
``

Damit müßte man das Problem wenigstens nur an einer Stelle umgehen.

**Comment by jodeutmann** [comment]
Ja richtig, eine vernünftige Lösung wäre die Bereinigung des Katasterbestandes. Ich werde das dort mal ansprechen. Für die Zwischenzeit: Löst die v.g. "Umgehung" über das Script auch den "drehwinkel=0" Fall?

**Comment by jef-n** [comment]
Autsch, natürlich nicht.  Korrigiert.
