### ISSUE TITLE
SVG Darstellung in OS X

### ISSUE THREAD

**Issue by tiehfood** [norBIT/alkisplugin#16]
Die SVG-Dateien werden unter QGIS 2.14 und OS X nicht richtig dargestellt:

![b](https://cloud.githubusercontent.com/assets/22456525/18847991/a2fc4686-842c-11e6-8063-4247a3a968d5.png)

**Comment by tiehfood** [comment]
Ich denke es liegt nicht an QGIS sondern der Pythonversion von OS X. Irgendwelche Vorschläge, wie ich das beheben könnte?
Zu Beginn bekam ich bei der Verwendung des Plugins folgende Fehlermeldung:
File "~/.qgis2/python/plugins/alkisplugin/qgisclasses.py", line 72, in __init__
		self.leSERVICE.setText( s.value( "service", "" ) )
		TypeError: setText(self, QString): argument 1 has unexpected type 'QPyNullVariant'

Diesen konnte ich (anscheinend) beheben, indem ich in den Zeilen mit s.value() hinter "" ein , type=str einfügte:
self.leSERVICE.setText( s.value( "service", ""**, type=str** ) )
Danach ließ sich das Plugin verwenden, leider mit dem oben genannten Problem der SVG-Darstellung...

**Comment by tiehfood** [comment]
Gibt es eine Chance auf Behebung des Problems?
Bin ansonsten mit dem Plugin sehr zufrieden.

**Comment by jef-n** [comment]
Werden die SVG-Pfade richtig eingetragen?   Einstellungen/Optionen, Reiter System, SVG-Pfade.  Dort sollte das svg-Verzeichnis des Plugins auftauchen (`$HOME/.qgis2/python/plugins/alkisplugin/svg`).

**Comment by tiehfood** [comment]
Ich musste den Pfad manuell hinzufügen, hat aber leider nichts an der Darstellung geändert.
