### ISSUE TITLE
DB-Verbindung vom Layer ableiten

### ISSUE THREAD

**Issue by tommytom73** [norBIT/alkisplugin#23]
Hallo Zusammen

Gibt es die Möglichkeit für die Abfrage des Flurstücksnachweis nicht immer die DB-Verbindung über das Menu umstellen zu müssen? Ich habe jetzt in einem Projekt 3 unterschiedliche ALKIS Datenstände von 3 aufeinanderfolgenden Jahren und um mir die Flurstücksinformationen (Eigentümer, Nutzung usw.) für die unterschiedlichen Jahren anzeigen zu lassen muss man immer erst die DB umstellen. Kann man diese Informationen nicht vom Layer selbst ableiten? Dort stehen doch alle Informationen über die Datenbankverbindung drin.
MfG Hartwig

**Comment by jef-n** [comment]
Im Moment ist die Abfrage unabhängig vom aktiven Layer.  Es wird in der eingestellten Datenbank bei der geklickten Koordinate gesucht.  Man könnte aber die Verbindungsdaten des aktuellen Layers vorziehen, wenn es ein ALKIS-Layer ist.

**Comment by tommytom73** [comment]
Ich würde es für sinnvoll erachten (jedenfalls für die Anzeige des Flurstücknachweis) das beim Klicken auf den Layer (Grenzen Flurstücke) oder der oberste Ordner der ALKIS Layer der Flurstücksnachweis die Verbindungsdaten zur Datenbank ausgelesen werden um dann die richtigen Daten im Flurstücksnachweis anzeigen zu lassen.
 
![image](https://user-images.githubusercontent.com/24441890/33175341-c44d911a-d05b-11e7-82a0-90e389bb723c.png)

**Comment by jef-n** [comment]
Fixed in ed2e2c400
