### ISSUE TITLE
Modellarten werden nicht angezeigt

### ISSUE THREAD

**Issue by achimwessling** [norBIT/alkisplugin#25]
Hallo,

im Konfigurationsdialog unter Darstellung werden keine Modellarten angezeigt. Egal ob ich den Signaturkatalog **Farbe** oder **s/w** wähle.

Ich vermute, dass dies dann auch in der Folge den Fehler auslöst, dass ich keine 'Layer einbinden' kann.

Wo in den DB werden die Modellarten gepflegt. Die Tabelle `aa_advstandardmodell` enthält zumindest Werte.

Ich bin für jeden Hinweis dankbar!

**Comment by jef-n** [comment]
Die Liste wird mit den verwendeten Modelle gefüllt.  Was ergibt die Abfragen aus [qgisclasses.py](https://github.com/norBIT/alkisplugin/blob/master/qgisclasses.py#L137) in der verwendeten Datenbank?

**Comment by achimwessling** [comment]
Alle `po_`-Tabellen sind leer! Werden die durch den Post-Process gefüllt?

Wenn ich mir meine Logs ansehe, würde ich sagen, da ist nichts gelaufen, ob wohl es eigentlich hätte passieren sollen.

Ich nutze **nicht die GUI** zum Import, sondern das Shell-Script mit einer Konfigurationsdatei. 
Wenn ich nicht explizit 'exit' in der Konfigurationsdatei verwende, sollte doch eigentlich der Post-Process ausgeführt werden!?

Kann ich eine Konfigurationsdatei so anlegen, dass ausschließlich das Post-Processing angestoßen wird? Z.B. so:

```
PG:host=postgis4postnas dbname=alkis user=postgres password=??????
epsg:25832
update
log
fnbruch on
pgverdraengen on
```

**Comment by jef-n** [comment]
Fixed in norBIT/alkisimport@4461c39

`epsg` allerdings ohne Doppelpunkt.

**Comment by achimwessling** [comment]
Sorry,

aber leider funktioniert der Script-Import jetzt nicht mehr, wenn eine Liste von XML-Files folgt.

Ist vermutlich bedingt durch den Fix?!

**Comment by jef-n** [comment]
Moin Achim,

On Tue, 20. Feb 2018 at 18:11:51 +0000, Achim Weßling wrote:
> Sorry,
 
> aber leider funktioniert der Script-Import jetzt nicht mehr, wenn eine Liste
> von XML-Files folgt.
 
> Ist vermutlich bedingt durch den Fix?!

Nein, nur geht's jetzt weiter als vorher.  Bei unkomprimierten XML-Dateien
wurde die das Ergebnis der Größenabfrage fälschlicherweise auf 0 gesetzt, wenn
sie erfolgreich war, statt wenn sie fehlschlug und das addieren der "leeren"
Größe führte dann zum Abbruch.  Gefixt in 4d74d0570 und 6bd6125a5.


Jürgen


-- 
Jürgen E. Fischer         norBIT GmbH               Tel. +49-4931-918175-31
Dipl.-Inf. (FH)           Rheinstraße 13            Fax. +49-4931-918175-50
Software Engineer         D-26506 Norden               http://www.norbit.de

**Comment by achimwessling** [comment]
DANKE!
