### ISSUE TITLE
'QgsDataSourceURI' object has no attribute 'dbname'

### ISSUE THREAD

**Issue by WalterWHeisenberg** [norBIT/alkisplugin#26]
Hallo,
habe gerade norGIS ALKIS Version 2.0.22  unter QGIS 2.18.16 versucht zu installieren.
Leider scheitert die Installation mit folgendem Fehler:
```
Diese Erweiterung ist defekt
'QgsDataSourceURI' object has no attribute 'dbname'
```
Vielleicht kann sich das jemand ansehen.

Danke sehr!
Gruß
WalterWHeisenberg

**Comment by jef-n** [comment]
Fixed in c8d4760bb1
