### ISSUE TITLE
Alkisplugin legt keine Layerstruktur an

### ISSUE THREAD

**Issue by schorsch2** [norBIT/alkisplugin#37]
Seit kurzem funktioniert das alkisplugin nicht mehr. Beim Aufruf von "Layer einbinden" läuft nur kurz ein blauer Streifen- und das wars, auch keine Fehlermeldungen.

QGIS-Version | 3.16.2-Hannover | QGIS-Codeversion | f1660f9da5
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | ComplexGmlInfo; Hqgis; inspireatomclient; m150xml; postgis_geoprocessing; qfieldsync; QuickOSM; SaxonyCadastralParcels; SuperLabeling; wfsclient; db_manager; processing; alkisplugin

**Comment by jef-n** [comment]
Leider nicht reproduzierbar.

**Comment by schorsch2** [comment]
Ich habe die Datenbank neu angelegt und jetzt erscheinen die Layer wieder wie sie sollen. Vielen Dank für die ausgesprochen nützlichen ALKIS- Programme!
