### ISSUE TITLE
QGIS Authentifizierung speichert neben authcfg auch user / password lesbar in Projektdatei

### ISSUE THREAD

**Issue by dassau** [norBIT/alkisplugin#38]
Hallo Jürgen,

wenn man die einfache QGIS Authentifizierung wählt, um Benutzer und Passwort in die lokale AuthentifizierungsDB zu speichern, ALKIS Layer einbindet und dann das Ganze als QGIS Projekt speichert, wird in der QGIS Projektdatei neben der authcfg auch user und password lesbar gespeichert.

<datasource> ... user='benutzer' password='passwort' authcfg=eu74jnt ... </datasource>

Grüße Otto

**Comment by jef-n** [comment]
Benutzername und Paßwort müßten aus dem ersten Reiter stammen.  Dort sollte man nichts angeben, wenn man Benutzername und Paßwort über authcfg angeben möchte.

**Comment by dassau** [comment]
Stimmt, da stehen sie noch - danke!
