### ISSUE TITLE
WMS über QGIS2web

### ISSUE THREAD

**Issue by DennisW90** [norBIT/alkisplugin#40]
Hallo, gibt es eine Möglichkeit die Layerdarsetllung des Plugins über ein QGIS2web als WMS bereitzustellen?

Bei dem Einsatz vonQGis2web kommt folgende Python Fehlermeldung:

Es scheint Probleme mit den beschriftungslayern und bestimmten Markern zu geben. 

Creating OpenLayers map...
Exporting libraries... done
Exporting layers...
Exporting Flächen (Wohnbauflächen) to JSON... done
Exporting Grenzen (Wohnbauflächen) to JSON... done
Exporting Flächen (Industrie und Gewerbe) to JSON... done
Exporting Grenzen (Industrie und Gewerbe) to JSON... done
Exporting Beschriftungen (Industrie und Gewerbe) to JSON... done
Exporting Flächen (Gewässer) to JSON... done
Exporting Grenzen (Gewässer) to JSON... done
Exporting Linien (Gewässer) to JSON... done
Exporting Punkte (Gewässer) to JSON... done
Exporting Beschriftungen (Gewässer) to JSON... done
Exporting Flächen (Vegetation) to JSON... done
Exporting Grenzen (Vegetation) to JSON... done
Exporting Punkte (Vegetation) to JSON... done
Exporting Grenzen (Verkehr) to JSON... done
Exporting Flächen (Rechtliche Festlegungen) to JSON... done
Exporting Grenzen (Rechtliche Festlegungen) to JSON... done
Exporting Beschriftungen (Rechtliche Festlegungen) to JSON... done
Exporting Grenzen (Politische Grenzen) to JSON... done
Exporting Beschriftungen (Politische Grenzen) to JSON... done
Exporting Grenzen (Politische Grenzen) to JSON... done
Exporting Beschriftungen (Politische Grenzen) to JSON... done
Exporting Grenzen (Politische Grenzen) to JSON... done
Exporting Beschriftungen (Politische Grenzen) to JSON... done
Exporting Linien (Politische Grenzen) to JSON... done
Exporting Beschriftungen (Lagebezeichnungen) to JSON... done
Exporting Flächen (Gebäude) to JSON... done
Exporting Grenzen (Gebäude) to JSON... done
Exporting Beschriftungen (Gebäude) to JSON... done
Exporting Linien (Flurstücke) to JSON... done
Exporting Beschriftungen (Flurstücke) to JSON... done
Exporting Grenzen (Flurstücke) to JSON... done
Exporting Punkte (Flurstücke) to JSON... done
Exporting Punktmarkierung to JSON... done
Exporting Linienmarkierung to JSON... done
Exporting Flächenmarkierung to JSON... done
Exporting Jagd-Flächenmarkierung to JSON... done done
Exception in layer Beschriftungen__Industrie_und_Gewerbe__6c7d4b48_bd6a_4682_960f_d8c9b085b345 with renderer SINGLE: MARKER SYMBOL (1 layers) color 232,113,141,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Punkte__Gewässer__8b73d718_a358_4d64_8eb2_e61bc57993cf with renderer CATEGORIZED: idx signaturnummer 3488::Fließgewässer::MARKER SYMBOL (1 layers) color 35,35,35,255:1 3490::Gewässer::MARKER SYMBOL (1 layers) color 35,35,35,255:1 : Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 54, in exportStyles layer_alpha, feedback) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 245, in categorized feedback)) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 497, in getSymbolAsStyle if symbol.dataDefinedAngle().useExpression(): AttributeError: 'QgsProperty' object has no attribute 'useExpression' 
Exception in layer Beschriftungen__Gewässer__f49c0a5a_6c34_4f47_9e4b_07376f84618a with renderer SINGLE: MARKER SYMBOL (1 layers) color 133,182,111,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Punkte__Vegetation__e2e51330_97f1_4b05_aa36_2e113dae8bb5 with renderer CATEGORIZED: idx signaturnummer 3413::Gras::MARKER SYMBOL (1 layers) color 35,35,35,255:1 3462::Mischwald::MARKER SYMBOL (1 layers) color 35,35,35,255:1 3470::Mischwald::MARKER SYMBOL (1 layers) color 35,35,35,255:1 3480::Unland::MARKER SYMBOL (1 layers) color 35,35,35,255:1 3460::Nadelwald::MARKER SYMBOL (1 layers) color 35,35,35,255:1 : Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 54, in exportStyles layer_alpha, feedback) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 245, in categorized feedback)) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 497, in getSymbolAsStyle if symbol.dataDefinedAngle().useExpression(): AttributeError: 'QgsProperty' object has no attribute 'useExpression' 
Exception in layer Beschriftungen__Rechtliche_Festlegungen__84b3de1b_1d85_43ed_b529_100f945a0525 with renderer SINGLE: MARKER SYMBOL (1 layers) color 152,125,183,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Beschriftungen__Politische_Grenzen__d31bf684_dbe3_422d_a583_1b523389db26 with renderer SINGLE: MARKER SYMBOL (1 layers) color 243,166,178,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Beschriftungen__Politische_Grenzen__ea28e73a_787d_4fdd_b9ed_8d6b4074f9b1 with renderer SINGLE: MARKER SYMBOL (1 layers) color 133,182,111,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Beschriftungen__Politische_Grenzen__3779f26f_ce7f_479e_b80f_8aa666e870ce with renderer SINGLE: MARKER SYMBOL (1 layers) color 196,60,57,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Linien__Politische_Grenzen__f97614ce_0ee9_4d5e_a36d_4e7b14b0a921 with renderer CATEGORIZED: idx signaturnummer 2012::Flurgrenze::LINE SYMBOL (5 layers) color 0,0,0,0:1 2014::Gemarkungsgrenze::LINE SYMBOL (4 layers) color 0,0,0,0:1 2022::Gemeindegrenze::LINE SYMBOL (3 layers) color 0,0,0,0:1 : Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 54, in exportStyles layer_alpha, feedback) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 245, in categorized feedback)) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 565, in getSymbolAsStyle color = getRGBAColor(props["color"], alpha) KeyError: 'color' 
Exception in layer Beschriftungen__Lagebezeichnungen__ea2924a0_e0b4_47ef_b635_a435df1f9eb7 with renderer SINGLE: MARKER SYMBOL (1 layers) color 232,113,141,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Beschriftungen__Gebäude__89461335_2803_4e81_8cda_93ae9c879ce7 with renderer SINGLE: MARKER SYMBOL (1 layers) color 243,166,178,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Beschriftungen__Flurstücke__04533d2c_b11f_4db0_ad16_8bbfc84d7581 with renderer SINGLE: MARKER SYMBOL (1 layers) color 190,178,151,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero 
Exception in layer Punkte__Flurstücke__cb6fa06d_384e_4908_adbc_e7220575bf16 with renderer CATEGORIZED: idx signaturnummer 3020::Abgemarkter Grenzpunkt::MARKER SYMBOL (1 layers) color 35,35,35,255:1 : Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 54, in exportStyles layer_alpha, feedback) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 245, in categorized feedback)) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 497, in getSymbolAsStyle if symbol.dataDefinedAngle().useExpression(): AttributeError: 'QgsProperty' object has no attribute 'useExpression' 
Writing HTML... done
Writing Layer Search... done
Success

Exported to C:\Users\dez3admin\AppData\Local\Temp\qgis2web

Hat jemand diesbezüglich schon Erfahrungen gemacht?
Was für Möglichkeiten gibt es um die Layer in ihrer Darstellungsform als WMS bereit zustellen? Was kann geändert werden damit das QGIS2web Plugin die Layerstruktur annimmt?

Liebe Grüße und Danke im Voraus

**Comment by jef-n** [comment]
> Hallo, gibt es eine Möglichkeit die Layerdarsetllung des Plugins über ein QGIS2web als WMS bereitzustellen?

Macht qgis2web überhaupt WMS?  Kommte da nicht "nur" eine Seite mit openlayers oder leaflet heraus?  QGIS-Server macht WMS.
 
> Bei dem Einsatz vonQGis2web kommt folgende Python Fehlermeldung:
> Exception in layer Beschriftungen__Industrie_und_Gewerbe__6c7d4b48_bd6a_4682_960f_d8c9b085b345 with renderer SINGLE: MARKER SYMBOL (1 layers) color 232,113,141,255: Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 78, in exportStyles bufferColor, bufferWidth) = getLabelFormat(layer) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 193, in getLabelFormat max = 1 / ((1 / max) * 39.37 * 90.7) ZeroDivisionError: float division by zero
> Exception in layer Punkte__Gewässer__8b73d718_a358_4d64_8eb2_e61bc57993cf with renderer CATEGORIZED: idx signaturnummer 3488::Fließgewässer::MARKER SYMBOL (1 layers) color 35,35,35,255:1 3490::Gewässer::MARKER SYMBOL (1 layers) color 35,35,35,255:1 : Traceback (most recent call last): File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 54, in exportStyles layer_alpha, feedback) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 245, in categorized feedback)) File "C:/Users/dez3admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web\olStyleScripts.py", line 497, in getSymbolAsStyle if symbol.dataDefinedAngle().useExpression(): AttributeError: 'QgsProperty' object has no attribute 'useExpression'

Das sieht nach qgis2web-Fehlern für Tom aus => https://github.com/tomchadwin/qgis2web/issues
