### ISSUE TITLE
Bei Wohn/Teileigentum fehlen Eigentümer im Flurstücksnachweis

### ISSUE THREAD

**Issue by bstroebl** [norBIT/alkisplugin#6]
Moin Jürgen,
wird für ein "Aufgeteiltes Grundstück WEG" der Flurstücksnachweis angezeigt, wird nur für den untersten Anteil die Namensinformation angezeigt.

Grüße

Bernhard

**Comment by jef-n** [comment]
Fixed in 0aaafc8
