### ISSUE TITLE
Baulasten

### ISSUE THREAD

**Issue by bstroebl** [norBIT/alkisplugin#7]
Hallo Jürgen,

bei mir werden die Baulasten in der Karte nicht angezeigt, Ich würde sie irgendwo in "rechtliche Festlegungen" vermuten. In ax_bauraumoderbodenordnungsrecht sind die Baulasten enthalten, sie werden aber offensichtlich nicht in die norbit-ALKIS-Tabellen übernommen.

**Comment by jef-n** [comment]
Es ging um die Beschriftung - die Grenze wurde schon dargestellt.
Die GeoInfoDok selbst hat für die Beschriftung nur eine Angabe für BW.  Dort wird allerdings auch noch ein anderer Schlüssel als 2610 nämlich 7865 für die Art der Festlegung Baulast verwendet. Im ALKIS-SK RP kommt das allerdings auch vor, dass 2610 mit "Baulast" beschriftet werden soll.   Besondere thüringer Festlegung gibt es allerdings nicht, daher sollte das so - ohne Beschriftung - in Ordnung sein.
