### ISSUE TITLE
Error loading ALKIS  data 

### ISSUE THREAD

**Issue by dassau** [norBIT/alkisplugin#8]
Moin Jürgen,

i get an error trying to load ALKIS data in QGIS 2.10.1.
 
File "/home/dassau/.qgis2/python/plugins/alkisplugin/alkisplugin.py", line 1143, in alkisimport
    "" if katalogTypeError: %d format: a number is required, not unicode

Python-Version: 2.7.6 (default, Jun 22 2015, 18:01:27) [GCC 4.8.2]
QGIS-Version: 2.10.1-Pisa Pisa, exported

Regards,
Otto

**Comment by jef-n** [comment]
Welcher Signaturkatalog ist in der Konfiguration gewählt (Was steht in "signaturkatalog" in ~dassau/.config/norBIT/norGIS-ALKIS-Erweiterung.conf)?

**Comment by dassau** [comment]
Dort steht signaturkatalog=-1

**Comment by dassau** [comment]
Danke! Klappt wieder.
